SELECT * FROM db.student;
SELECT * FROM db.course;
SELECT * FROM db.grade;
SELECT * FROM db.SPRING_SESSION_ATTRIBUTES;
SELECT * FROM db.SPRING_SESSION;
SELECT * FROM db.authorities;
SELECT * FROM db.users;
