package com.ltp.gradesubmission.entity;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "user_data")
@Data
@Builder
@RequiredArgsConstructor
@AllArgsConstructor
@ToString(callSuper = true)
public class UserData implements Serializable {
    @NonNull
    @Id //this should not be autogenerated
    @Column(name = "username")
    @Size(min = 4, message = "Username length must be at least 4")
    @NotBlank(message = "Username can not be blank")
    private String username;

    @NonNull
    @Column(name = "password", nullable = false)
    @Size(min = 4, message = "Password length must be at least ")
    @NotBlank(message = "Password can not be blank")
    private String password;

    @NonNull
    @Column(name = "name")
    @NotBlank(message = "Firstname can not be blank")
    private String firstname;

    @NonNull
    @Column(name = "surname")
    @NotBlank(message = "Surname can not be blank")
    private String surname;

    @NonNull
    @Column(name = "email")
    @NotBlank(message = "Email can not be blank")
    private String email;

    @NonNull
    @Column(name = "age")
    @Min(value = 0, message = "Age can not be less than 0")
    private Integer age;

    //cascade: when a user is deleted, all authorities pointing to it are deleted as well
    //FetchType.EAGER: avoids LazyInitializationException
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "username", cascade = CascadeType.ALL)
    private List<UserAuthority> authorities;

    //index = 0 --> old password;  index = 1 new password
    @Transient //this value is excluded by Hibernate
    private List<String> passwordChange;

    @Transient
    private String role;

    public UserData() { };
}
