DROP TABLE IF EXISTS db.SPRING_SESSION_ATTRIBUTES;
DROP TABLE IF EXISTS db.SPRING_SESSION;
DROP TABLE IF EXISTS db.authorities;
DROP TABLE IF EXISTS db.use;
DROP TABLE IF EXISTS db.user_authority;
DROP TABLE IF EXISTS db.uesr_data;
